-- Table for storing user memories with authentication
CREATE TABLE public.retain_auth_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    favourite BOOLEAN DEFAULT false,
    metadata JSONB,
    fts TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('english', 
            COALESCE(metadata->>'title', '') || ' ' || 
            COALESCE(metadata->>'summary', '') || ' ' || 
            COALESCE(array_to_string(ARRAY(SELECT jsonb_array_elements_text(metadata->'keywords')), ' '), '')
        )
    ) STORED
);

-- Index for full-text search
CREATE INDEX idx_retain_auth_memory_fts ON public.retain_auth_memory USING gin(fts);

-- Index for timestamp queries
CREATE INDEX idx_retain_auth_memory_created_at ON public.retain_auth_memory (created_at);

-- Index for favourite queries  
CREATE INDEX idx_retain_auth_memory_favourite ON public.retain_auth_memory (favourite);

-- Index for JSONB queries on metadata
CREATE INDEX idx_retain_auth_memory_metadata ON public.retain_auth_memory USING gin(metadata);

-- Enable Row Level Security (RLS)
ALTER TABLE public.retain_auth_memory ENABLE ROW LEVEL SECURITY;

-- Policy to allow users to only see their own data
CREATE POLICY "Users can only access their own memories" ON public.retain_auth_memory
    FOR ALL USING (auth.uid() IS NOT NULL);

-- Function for executing dynamic SQL (used by searchNLPSql endpoint)
CREATE OR REPLACE FUNCTION public.execute_sql(query_string text)
RETURNS TABLE(id bigint, created_at timestamptz, metadata jsonb)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY EXECUTE query_string;
END;
$$;

COMMENT ON TABLE public.retain_auth_memory IS 'Stores user memories with AI-extracted metadata, full-text search, and authentication';
COMMENT ON FUNCTION public.execute_sql IS 'Executes dynamic SQL queries for NLP search functionality';